// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.2
// source: static.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaticRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *StaticRequest) Reset() {
	*x = StaticRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_static_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticRequest) ProtoMessage() {}

func (x *StaticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_static_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticRequest.ProtoReflect.Descriptor instead.
func (*StaticRequest) Descriptor() ([]byte, []int) {
	return file_static_proto_rawDescGZIP(), []int{0}
}

func (x *StaticRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type StaticResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *StaticResponse) Reset() {
	*x = StaticResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_static_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticResponse) ProtoMessage() {}

func (x *StaticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_static_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticResponse.ProtoReflect.Descriptor instead.
func (*StaticResponse) Descriptor() ([]byte, []int) {
	return file_static_proto_rawDescGZIP(), []int{1}
}

func (x *StaticResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_static_proto protoreflect.FileDescriptor

var file_static_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x24, 0x0a, 0x0e, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x42, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x32, 0x4c, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3b, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x08,
	0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_static_proto_rawDescOnce sync.Once
	file_static_proto_rawDescData = file_static_proto_rawDesc
)

func file_static_proto_rawDescGZIP() []byte {
	file_static_proto_rawDescOnce.Do(func() {
		file_static_proto_rawDescData = protoimpl.X.CompressGZIP(file_static_proto_rawDescData)
	})
	return file_static_proto_rawDescData
}

var file_static_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_static_proto_goTypes = []interface{}{
	(*StaticRequest)(nil),  // 0: proto.StaticRequest
	(*StaticResponse)(nil), // 1: proto.StaticResponse
}
var file_static_proto_depIdxs = []int32{
	0, // 0: proto.StaticService.Stream:input_type -> proto.StaticRequest
	1, // 1: proto.StaticService.Stream:output_type -> proto.StaticResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_static_proto_init() }
func file_static_proto_init() {
	if File_static_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_static_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaticRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_static_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaticResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_static_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_static_proto_goTypes,
		DependencyIndexes: file_static_proto_depIdxs,
		MessageInfos:      file_static_proto_msgTypes,
	}.Build()
	File_static_proto = out.File
	file_static_proto_rawDesc = nil
	file_static_proto_goTypes = nil
	file_static_proto_depIdxs = nil
}
